export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES';
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS';
export const GET_PRODUCT_CATEGORIES_ERROR = 'GET_PRODUCT_CATEGORIES_ERROR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const GET_TOP_SALES_PRODUCTS = 'GET_TOP_SALES_PRODUCTS';
export const GET_TOP_SALES_PRODUCTS_SUCCESS = 'GET_TOP_SALES_PRODUCTS_SUCCESS';
export const GET_TOP_SALES_PRODUCTS_ERROR = 'GET_TOP_SALES_PRODUCTS_ERROR';
export const GET_TOP_NEW_PRODUCTS = 'GET_TOP_NEW_PRODUCTS';
export const GET_TOP_NEW_PRODUCTS_SUCCESS = 'GET_TOP_NEW_PRODUCTS_SUCCESS';
export const GET_TOP_NEW_PRODUCTS_ERROR = 'GET_TOP_NEW_PRODUCTS_ERROR';
export const GET_TOP_FEATURED_PRODUCTS = 'GET_TOP_FEATURED_PRODUCTS';
export const GET_TOP_FEATURED_PRODUCTS_SUCCESS = 'GET_TOP_FEATURED_PRODUCTS_SUCCESS';
export const GET_TOP_FEATURED_PRODUCTS_ERROR = 'GET_TOP_FEATURED_PRODUCTS_ERROR';
export const GET_TOP_VIEW_PRODUCTS = 'GET_TOP_VIEW_PRODUCTS';
export const GET_TOP_VIEW_PRODUCTS_SUCCESS = 'GET_TOP_VIEW_PRODUCTS_SUCCESS';
export const GET_TOP_VIEW_PRODUCTS_ERROR = 'GET_TOP_VIEW_PRODUCTS_ERROR';

export const GET_COLORS = 'GET_COLORS';
export const GET_COLORS_SUCCESS = 'GET_COLORS_SUCCESS';
export const GET_COLORS_ERROR = 'GET_COLORS_ERROR';

export const GET_SIZES = 'GET_SIZES';
export const GET_SIZES_SUCCESS = 'GET_SIZES_SUCCESS';
export const GET_SIZES_ERROR = 'GET_SIZES_ERROR';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';

export const GET_CARTS = 'GET_CARTS';
export const GET_CARTS_SUCCESS = 'GET_CARTS_SUCCESS';
export const GET_CARTS_ERROR = 'GET_CARTS_ERROR';
export const CREATE_CART = 'CREATE_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const DELETE_CART = 'DELETE_CART';
export const DELETE_ALL_CART = 'DELETE_ALL_CART';

export const GET_FAVORITE_PRODUCTS = 'GET_FAVORITE_PRODUCTS';
export const GET_FAVORITE_PRODUCTS_SUCCESS = 'GET_FAVORITE_PRODUCTS_SUCCESS';
export const GET_FAVORITE_PRODUCTS_ERROR = 'GET_FAVORITE_PRODUCTS_ERROR';