export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES';
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS';
export const GET_PRODUCT_CATEGORIES_ERROR = 'GET_PRODUCT_CATEGORIES_ERROR';
export const CREATE_PRODUCT_CATEGORY = 'CREATE_PRODUCT_CATEGORY';
export const UPDATE_PRODUCT_CATEGORY = 'UPDATE_PRODUCT_CATEGORY';
export const DELETE_PRODUCT_CATEGORY = 'DELETE_PRODUCT_CATEGORY';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const GET_PRODUCT_DETAIL_SALES = 'GET_PRODUCT_DETAIL_SALES';
export const GET_PRODUCT_DETAIL_SALES_SUCCESS = 'GET_PRODUCT_DETAIL_SALES_SUCCESS';
export const GET_PRODUCT_DETAIL_SALES_ERROR = 'GET_PRODUCT_DETAIL_SALES_ERROR';
export const CREATE_PRODUCT_DETAIL_SALE = 'CREATE_PRODUCT_DETAIL_SALE';
export const UPDATE_PRODUCT_DETAIL_SALE = 'UPDATE_PRODUCT_DETAIL_SALE';
export const DELETE_PRODUCT_DETAIL_SALE = 'DELETE_PRODUCT_DETAIL_SALE';

export const GET_COLORS = 'GET_COLORS';
export const GET_COLORS_SUCCESS = 'GET_COLORS_SUCCESS';
export const GET_COLORS_ERROR = 'GET_COLORS_ERROR';
export const CREATE_COLOR = 'CREATE_COLOR';
export const UPDATE_COLOR = 'UPDATE_COLOR';
export const DELETE_COLOR = 'DELETE_COLOR';

export const GET_SIZES = 'GET_SIZES';
export const GET_SIZES_SUCCESS = 'GET_SIZES_SUCCESS';
export const GET_SIZES_ERROR = 'GET_SIZES_ERROR';
export const CREATE_SIZE = 'CREATE_SIZE';
export const UPDATE_SIZE = 'UPDATE_SIZE';
export const DELETE_SIZE = 'DELETE_SIZE';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';
export const UPDATE_ORDER = 'UPDATE_ORDER';